apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gitops-app
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/Musty2025x/gitops-k8s-config.git
    targetRevision: main
    path: dev

  destination:
    server: https://kubernetes.default.svc
    namespace: dev

  syncPolicy:
    automated:
      prune: true        # delete resources removed from Git
      selfHeal: true     # revert manual changes to cluster
    syncOptions:
      - CreateNamespace=true